### ISSUE TITLE
Publish plugin fork

### ISSUE THREAD

**Issue by ghost** [darthorimar/intellij-scala-to-kotlin#3]
Hello, @darthorimar!
I've seen that this plugin is under "Unlicensed". Even so, I want to ask you, can I publish this plugin built for IDEA 2018.3 and 2019.1 (and probably other versions) for others in JB plugin repository? I made it work on 2018.3 and 2019.1 in my fork.
Me and my friends are interested in this plugin, because we want to migrate one Android app written in Scala to Kotlin (for some reasons). It will be easier to others if I'll publish this plugin.
Also, I think it will be better to change plugin id ("darthorimar.scalaToKotlin") to not to associate this plugin with your JB account.
What do you think?

**Comment by darthorimar** [comment]
Hi, @jbreathe! 

Feel free to publish it and make any changes you consider appropriate :)

**Comment by ghost** [comment]
Thank you, @darthorimar!
